### ISSUE TITLE
Add Server distribution support

### ISSUE THREAD

**Issue by abread** [TechnicPack/TechnicSolder#20]
My suggestion is to add some stuff to the api to make Solder have a behaviour similar to the current but for servers! The server binary could also come with some sort of maintenance script for updating the modpack (and it would backup the current installation of the server...)

For example: (modlibrary.yml)

``` yaml
mods:
    modx-that-has-no-universal-jar:
        name: "this is a mod, stupid but a mod"
        installtype: "zip"
        versions:
            1.0:
                server: 
```

In the "server:" you could just leave it that way and it will search for [modslug]/[modslug]-[version]-server.zip

And the server would have a separate "modpack-server.yml" file (because mods like "Custom LAN Ports" are made just for the minecraft client).

I'm a Web Developer but:
1. This would need to be implemented deeply in the Technic Platform (website, not the launcher)
2. I'm not familiar with Laravel

In the future I might make the API and some sort of "ServerInstaller.jar" but I have some projects going on and I don't have time :(
